# Generated by Django 2.0.7 on 2018-08-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tile', models.ImageField(upload_to='')),
                ('img_main', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField(blank=True, default='')),
                ('text', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('bg_color', models.CharField(default='#f2f2f2', max_length=7)),
                ('image_type', models.CharField(choices=[('Desk', 'Desktop'), ('Mobile', 'Mobile'), ('Logo', 'Logo'), ('Full Width', 'Full Width')], default='Desk', max_length=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='public.Project')),
            ],
        ),
    ]
