# Generated by Django 2.0.7 on 2018-08-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20180803_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
        migrations.RemoveField(
            model_name='project',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='project',
            name='style',
        ),
    ]
