# Generated by Django 2.0.7 on 2018-08-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20180803_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='left_images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
