# Generated by Django 2.0.7 on 2018-08-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_auto_20180807_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='objective',
        ),
    ]
