# Generated by Django 2.0.7 on 2018-08-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_projectimage_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='bg_color',
            field=models.CharField(default='#f2f2f2', max_length=7),
        ),
    ]
