# Generated by Django 2.0.7 on 2018-08-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_auto_20180808_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='image_type',
            field=models.CharField(choices=[('Desk', 'Desktop'), ('Mobile', 'Mobile'), ('Logo', 'Logo'), ('Full Width', 'Full Width')], default='Desk', max_length=4),
        ),
    ]
