# Generated by Django 2.0.7 on 2018-08-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_project_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img_main',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
